fix(paxos): Proposers don't re-commit entries before the latest checkpoint
hydro-project/hydro pull request #1615
Opened 2024-12-19 19:30 UTC by davidchuyaya

Paxos proposers assign no-ops to holes in the log after receiving a quorum of p1bs. Acceptors delete log entries before the latest checkpoint, which means they will show up as holes in the proposer. The proposer should not propose any operations before the most recent checkpoint in a quorum of p1bs.

2025-01-07 22:48 UTC, shadaj requested changes
Looks like there are some conflicts too.

2025-01-07 22:48 UTC, shadaj commented on hydroflow_plus_test/src/cluster/paxos.rs
> +                -1
Instead of using signed integers, we should use an `Option<usize>` here.

2025-01-07 22:48 UTC, shadaj commented on hydroflow_plus_test/src/cluster/paxos.rs
> +        .into_stream()
Use `.zip` instead, no need to convert to a stream.

2025-01-07 22:48 UTC, shadaj commented on hydroflow_plus_test/src/cluster/paxos.rs
> +            |(max_slot, checkpoint)| (checkpoint + 1) as usize..max_slot
With an `Option`, above, here you should do `checkpoint.unwrap_or(0)`.

2025-01-07 22:49 UTC, shadaj commented
This is just an optimization right? The acceptors would just ignore the re-commits lower than the checkpoint?

2025-01-08 10:07 UTC, davidchuyaya commented
> This is just an optimization right? The acceptors would just ignore the re-commits lower than the checkpoint?

Don't think so, acceptors have no logic to ignore things based on the checkpoint, just to remove things from the log.

2025-01-08 17:36 UTC, shadaj commented
> Don't think so, acceptors have no logic to ignore things based on the checkpoint, just to remove things from the log.

What about https://github.com/hydro-project/hydro/pull/1615/files#diff-0c2b25ea57283b18a47e2b1c8cc30cdd470fde34d9ed6d06f8b45c1cb02976afR802

2025-01-08 17:38 UTC, shadaj commented on hydro_test/src/cluster/paxos.rs
> +    let p_p1b_max_checkpoint = accepted_logs.clone().fold_commutative(
In theory you could replace this with a `.map().flatten().max()`.

2025-01-08 17:39 UTC, shadaj approved these changes
One potential improvement, feel free to just merge though.

2025-01-09 00:31 UTC, davidchuyaya commented
> > Don't think so, acceptors have no logic to ignore things based on the checkpoint, just to remove things from the log.
> 
> What about https://github.com/hydro-project/hydro/pull/1615/files#diff-0c2b25ea57283b18a47e2b1c8cc30cdd470fde34d9ed6d06f8b45c1cb02976afR802

U right

2025-01-09 03:22 UTC, davidchuyaya commented on hydro_test/src/cluster/paxos.rs
> +    let p_p1b_max_checkpoint = accepted_logs.clone().fold_commutative(
Doesn't this change behavior from a stream that contains either None or Some(checkpoint) to an Optional stream that may contain checkpoint? Because then the later join with `p_log_to_try_commit` won't go through if there is no checkpoint right? Without the flatten maybe it's ok?

2025-01-09 06:41 UTC, shadaj commented on hydro_test/src/cluster/paxos.rs
> +    let p_p1b_max_checkpoint = accepted_logs.clone().fold_commutative(
True! You can fix this by adding an addition `.into_singleton()` which should convert the `Optional<T>` into `Singleton<Option<T>>`.

2025-01-09 08:54 UTC, davidchuyaya commented on hydro_test/src/cluster/paxos.rs
> +    let p_p1b_max_checkpoint = accepted_logs.clone().fold_commutative(
I'll just do `map().max()`, since Some(anything) > None so it works out

2025-01-09 09:29 UTC, merged